{
    'name': 'aaap',
    'version': '1.0',
    'summary': 'First aaap on Odoo',
    'description': 'First aaap on Odoo',
    'author': 'Your Name or Company',
    'website': 'http://www.example.com',
    'category': 'Uncategorized',
    'depends': ['base', 'account'],
    'data': [
        "security/ir.model.access.csv",
        "views/aaap_plaats_views.xml",
        "views/aaap_type_views.xml",
        "views/aaap_tags_views.xml",
        "views/aaap_clicker_views.xml",  
        "data/aaap_plaats.xml",
        "data/aaap_type.xml",
        "data/aaap_tags.xml",
        "views/account_move_views.xml",
        "views/aaap_menu_views.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'aaap/static/src/js/clicker_game.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}